"""Email notification — sends case study drafts via Resend."""

from __future__ import annotations

import logging
from datetime import datetime

import resend

from app.config import AppConfig

logger = logging.getLogger("casestudy.notify")


def send_case_study_email(
    brand_name: str,
    case_study: str,
    config: AppConfig,
) -> None:
    """Send a generated case study draft via Resend for review."""
    if not config.resend_api_key:
        logger.info("No RESEND_API_KEY set — skipping email")
        return
    if not config.resend_from_email:
        print("[EMAIL] No RESEND_FROM_EMAIL set — skipping email")
        return
    if not config.resend_to_email:
        print("[EMAIL] No RESEND_TO_EMAIL set — skipping email")
        return

    resend.api_key = config.resend_api_key

    date_str = datetime.now().strftime("%B %d, %Y")

    # Convert markdown-ish text to simple HTML
    body_html = case_study.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    body_html = body_html.replace("\n\n", "</p><p style='margin:0 0 16px 0;'>")
    body_html = body_html.replace("\n", "<br>")
    body_html = f"<p style='margin:0 0 16px 0;'>{body_html}</p>"

    html = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:0 auto;color:#1a1a1a;">
        <div style="background:linear-gradient(135deg,#6366f1,#4338ca);padding:24px 32px;border-radius:8px 8px 0 0;">
            <h1 style="color:white;margin:0;font-size:22px;">Case Study Draft</h1>
            <p style="color:#c7d2fe;margin:4px 0 0 0;font-size:14px;">{date_str} &middot; {brand_name}</p>
        </div>

        <div style="padding:16px 32px;background:#eef2ff;border:1px solid #e5e7eb;border-top:none;">
            <p style="margin:0;font-size:14px;color:#444;">
                Review this case study draft. Edit as needed before publishing.
            </p>
        </div>

        <div style="padding:24px 32px;background:#fff;border:1px solid #e5e7eb;border-top:none;font-size:15px;line-height:1.8;">
            {body_html}
        </div>

        <div style="padding:16px 32px;background:#f8fafc;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;font-size:12px;color:#6b7280;">
            Generated by Case Study Collector &middot; Powered by Agentway
        </div>
    </div>
    """

    try:
        result = resend.Emails.send({
            "from": config.resend_from_email,
            "to": config.resend_to_email,
            "subject": f"Case Study Draft — {brand_name} ({date_str})",
            "html": html,
        })
        email_id = result.get("id", "ok") if isinstance(result, dict) else str(result)
        print(f"[EMAIL] Sent successfully: {email_id} -> {', '.join(config.resend_to_email)}")
    except Exception as e:
        print(f"[EMAIL] Failed to send: {e}")
